version: '3.8'

services:
  backend:
    container_name: leave_backend
    build: ./Backend
    ports:
      - "3053:3053"
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=admin123
      - PGHOST=postgres
      - PGDATABASE=Leave
      - PGPORT=5432
    networks:
      - leave_net

  frontend:
    container_name: leave_frontend
    build: ./Frontend
    ports:
      - "8086:80"
    depends_on:
      - backend
    networks:
      - leave_net

  hr:
    container_name: leave_hr
    build: ./HR
    ports:
      - "8087:80"
    depends_on:
      - backend
    networks:
      - leave_net

  postgres:
    container_name: leave_postgres
    image: postgres:13
    ports:
      - "5453:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=Leave
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - leave_net

volumes:
  pgdata:

networks:
  leave_net:
    driver: bridge

